-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgz+OTWKrKgSGM+NIg
DxknuUCHCHdpv+S1fS89ac9j1bugCgYIKoZIzj0DAQehRANCAAQyHo41k5Mq1od0
zyYcoZD+ILZBn6wLcXo/DZ3idCFDAmc3LGOZEWJbBxdV7mVSdwsl/Vv9YPpqJZhP
stUUxNNR
-----END PRIVATE KEY-----